name: Notify Slack on Pull Request

on:
  pull_request:
    types: [review_requested]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send notification to Slack
      env:
        SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL: ${{ secrets.SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
        PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
        ASSIGNEE: ${{ github.event.pull_request.assignees[0].login }}
        PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Pull Request Review Requested",
          "attachments": [
            {
              "fallback": "Pull Request <${{ env.PULL_REQUEST_URL }}> requested review by ${{ env.REVIEWER }}",
              "color": "#36a64f",
              "pretext": "A new pull request review has been requested!",
              "title": "${{ env.PULL_REQUEST_TITLE }}",
              "title_link": "${{ env.PULL_REQUEST_URL }}",
              "text": "Repository: ${{ env.GITHUB_REPOSITORY }}\nRequested Reviewer: ${{ env.REVIEWER }}\nBy: ${{ env.GITHUB_ACTOR }}",
              "footer": "GitHub Actions",
              "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
            }
          ]
        }' $SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL
