name: run_full_examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 */3 * *'   # Runs at midnight every 3 days
  workflow_dispatch:

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  FAILURE_WEBHOOK: ${{secrets.FAILURE_WEBHOOK}}
  CHAIN: ethereum
  AWS_DEFAULT_REGION: eu-west-2
  AWS_SG_NAME: launch-wizard-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  run_full_examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14']
        python-version: ['3.10', '3.11']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-de33b6af53005037b463318d2628b5cfcaf39916 

      - name: Install release-executable
        run: |
          pip install dojo-compass 

      - name: Run run.py
        run: |
          python run.py 

      - name: Run run_aave.py
        run: |
          python run_aave.py

      - name: Run run_arbitrage.py
        run: |
          python run_arbitrage.py 


              

