name: run_snippets

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 */3 * *'   # Runs at midnight every 3 days
  workflow_dispatch:

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  FAILURE_WEBHOOK: ${{secrets.FAILURE_WEBHOOK}}
  CHAIN: ethereum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_snippets:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14']
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Setup dev environment
        uses: CompassLabs/workflows/.github/actions/setup_dojo_pypi@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Snippets first
        id: snippets_first_try
        continue-on-error: true
        run: |
          cd snippets
          ls . | xargs python

      - name: Run Snippets second
        id: snippets_second_try
        if: steps.snippets_first_try.outcome == 'failure'
        continue-on-error: false
        run: |
          cd snippets
          ls . | xargs python

      - name: Send failure message to slack
        if: failure()
        run: |
          curl $FAILURE_WEBHOOK