name: run_all

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: '*'
  workflow_dispatch:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  CHAIN: ethereum
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-14']
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Setup dev environment
        uses: CompassLabs/workflows/.github/actions/setup_dojo_pypi@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=policies --cov=agents --cov-report xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3