name: run_full_examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 */3 * *'   # Runs at midnight every 3 days
  workflow_dispatch:

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  FAILURE_WEBHOOK: ${{secrets.FAILURE_WEBHOOK}}
  CHAIN: ethereum

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_full_examples:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-14']
        python-version: ['3.10', '3.11']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup dev environment
        uses: CompassLabs/workflows/.github/actions/setup_dojo_pypi@main
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run example_backtest.py
        run: |
          python example_backtest.py 

      - name: Run everything in the examples/ folder
        run: |
          find examples -wholename "*run.py" -exec python {} \;


              

