name: run_all

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: '*'
  workflow_dispatch:
  schedule:
    # Run every 12 hours
    - cron: '0 */12 * * *'

env:
  RPC_URL: ${{ secrets.RPC_URL }}
  LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
  CHAIN: ethereum
  AWS_DEFAULT_REGION: eu-west-2
  AWS_SG_NAME: launch-wizard-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  test-all:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-14-xlarge']
        python-version: ['3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-de33b6af53005037b463318d2628b5cfcaf39916 

      - name: Install release-executable
        run: |
          pip install dojo-compass
          pip install pytest

      - name: Run tests
        run: |
          pip install pytest-cov
          pytest --cov=policies --cov=agents --cov-report xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
